name = "paste-web"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 本地开发配置
[dev]
port = 8787

# KV存储绑定
# 注意：本地开发时会自动创建临时的 KV 存储
[[kv_namespaces]]
binding = "PASTE_KV"
id = " "  # 本地开发时留空，wrangler 会自动创建临时存储
preview_id = ""  # 本地开发时留空

# 环境变量
[vars]
ADMIN_PASSWORD = "123456"
ACCESS_PASSWORD = ""  # 留空表示不需要访问密码，设置值则启用访问保护
RATE_LIMIT_MAX = "5"
RATE_LIMIT_WINDOW = "60"

# 生产环境配置
[env.production]
name = "paste-web-prod"

# 开发环境配置  
[env.development]
name = "paste-web-dev"
